<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140307145739 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimstate DROP FOREIGN KEY FK_3B9568EEA769DE27");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimstate ADD CONSTRAINT FK_3B9568EEA769DE27 FOREIGN KEY (claim) REFERENCES famelo_broensfin_domain_model_claim (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC353105CB86");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC353D82E92A");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC35EDCC8CAE");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC353105CB86 FOREIGN KEY (currentstate) REFERENCES famelo_broensfin_domain_model_claimstate (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC353D82E92A FOREIGN KEY (creditor) REFERENCES famelo_saas_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC35EDCC8CAE FOREIGN KEY (debtor) REFERENCES famelo_saas_domain_model_team (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC353D82E92A");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC35EDCC8CAE");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC353105CB86");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC353D82E92A FOREIGN KEY (creditor) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier) ON DELETE SET NULL");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC35EDCC8CAE FOREIGN KEY (debtor) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier) ON DELETE SET NULL");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC353105CB86 FOREIGN KEY (currentstate) REFERENCES famelo_broensfin_domain_model_claimstate (persistence_object_identifier) ON DELETE SET NULL");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimstate DROP FOREIGN KEY FK_3B9568EEA769DE27");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimstate ADD CONSTRAINT FK_3B9568EEA769DE27 FOREIGN KEY (claim) REFERENCES famelo_broensfin_domain_model_claim (persistence_object_identifier) ON DELETE SET NULL");
	}
}