<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140218151238 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_company_users_join DROP FOREIGN KEY FK_C68ACD68D01E5C72");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_company");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_company_users_join");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD creditor VARCHAR(40) DEFAULT NULL, ADD debtor VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC353D82E92A FOREIGN KEY (creditor) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC35EDCC8CAE FOREIGN KEY (debtor) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_8A7DDC353D82E92A ON famelo_broensfin_domain_model_claim (creditor)");
		$this->addSql("CREATE INDEX IDX_8A7DDC35EDCC8CAE ON famelo_broensfin_domain_model_claim (debtor)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_company (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_company_users_join (broensfin_company VARCHAR(40) NOT NULL, saas_user VARCHAR(40) NOT NULL, INDEX IDX_C68ACD68D01E5C72 (broensfin_company), INDEX IDX_C68ACD68858522EA (saas_user), PRIMARY KEY(broensfin_company, saas_user))");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_company_users_join ADD CONSTRAINT FK_C68ACD68858522EA FOREIGN KEY (saas_user) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_company_users_join ADD CONSTRAINT FK_C68ACD68D01E5C72 FOREIGN KEY (broensfin_company) REFERENCES famelo_broensfin_domain_model_company (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC353D82E92A");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC35EDCC8CAE");
		$this->addSql("DROP INDEX IDX_8A7DDC353D82E92A ON famelo_broensfin_domain_model_claim");
		$this->addSql("DROP INDEX IDX_8A7DDC35EDCC8CAE ON famelo_broensfin_domain_model_claim");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP creditor, DROP debtor");
	}
}