<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140219165844 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE famelo_broensfin_domain_model_claim_users_join");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimcomment CHANGE message message LONGTEXT NOT NULL");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD currentstate VARCHAR(40) DEFAULT NULL, DROP reference");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD CONSTRAINT FK_8A7DDC353105CB86 FOREIGN KEY (currentstate) REFERENCES famelo_broensfin_domain_model_claimstate (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_8A7DDC353105CB86 ON famelo_broensfin_domain_model_claim (currentstate)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_claim_users_join (broensfin_claim VARCHAR(40) NOT NULL, saas_user VARCHAR(40) NOT NULL, INDEX IDX_5BA453A81703F0B5 (broensfin_claim), INDEX IDX_5BA453A8858522EA (saas_user), PRIMARY KEY(broensfin_claim, saas_user))");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim_users_join ADD CONSTRAINT FK_5BA453A81703F0B5 FOREIGN KEY (broensfin_claim) REFERENCES famelo_broensfin_domain_model_claim (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim_users_join ADD CONSTRAINT FK_5BA453A8858522EA FOREIGN KEY (saas_user) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim DROP FOREIGN KEY FK_8A7DDC353105CB86");
		$this->addSql("DROP INDEX IDX_8A7DDC353105CB86 ON famelo_broensfin_domain_model_claim");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim ADD reference VARCHAR(255) NOT NULL, DROP currentstate");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimcomment CHANGE message message VARCHAR(255) NOT NULL");
	}
}