<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140217215059 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_claim (persistence_object_identifier VARCHAR(40) NOT NULL, reference VARCHAR(255) NOT NULL, externalreference VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, duedate DATETIME NOT NULL, creationdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_claim_users_join (broensfin_claim VARCHAR(40) NOT NULL, saas_user VARCHAR(40) NOT NULL, INDEX IDX_5BA453A81703F0B5 (broensfin_claim), INDEX IDX_5BA453A8858522EA (saas_user), PRIMARY KEY(broensfin_claim, saas_user))");
		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_claimstate (persistence_object_identifier VARCHAR(40) NOT NULL, claim VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, state VARCHAR(255) NOT NULL, INDEX IDX_3B9568EEA769DE27 (claim), UNIQUE INDEX flow_identity_famelo_broensfin_domain_model_claimstate (date), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_company (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_company_users_join (broensfin_company VARCHAR(40) NOT NULL, saas_user VARCHAR(40) NOT NULL, INDEX IDX_C68ACD68D01E5C72 (broensfin_company), INDEX IDX_C68ACD68858522EA (saas_user), PRIMARY KEY(broensfin_company, saas_user))");
		$this->addSql("CREATE TABLE famelo_broensfin_domain_model_claimcomment (persistence_object_identifier VARCHAR(40) NOT NULL, claim VARCHAR(40) DEFAULT NULL, user VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, message VARCHAR(255) NOT NULL, INDEX IDX_887576ECA769DE27 (claim), INDEX IDX_887576EC8D93D649 (user), UNIQUE INDEX flow_identity_famelo_broensfin_domain_model_claimcomment (date), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim_users_join ADD CONSTRAINT FK_5BA453A81703F0B5 FOREIGN KEY (broensfin_claim) REFERENCES famelo_broensfin_domain_model_claim (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim_users_join ADD CONSTRAINT FK_5BA453A8858522EA FOREIGN KEY (saas_user) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimstate ADD CONSTRAINT FK_3B9568EEA769DE27 FOREIGN KEY (claim) REFERENCES famelo_broensfin_domain_model_claim (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_company_users_join ADD CONSTRAINT FK_C68ACD68D01E5C72 FOREIGN KEY (broensfin_company) REFERENCES famelo_broensfin_domain_model_company (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_company_users_join ADD CONSTRAINT FK_C68ACD68858522EA FOREIGN KEY (saas_user) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimcomment ADD CONSTRAINT FK_887576ECA769DE27 FOREIGN KEY (claim) REFERENCES famelo_broensfin_domain_model_claim (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimcomment ADD CONSTRAINT FK_887576EC8D93D649 FOREIGN KEY (user) REFERENCES famelo_saas_domain_model_user (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claim_users_join DROP FOREIGN KEY FK_5BA453A81703F0B5");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimstate DROP FOREIGN KEY FK_3B9568EEA769DE27");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_claimcomment DROP FOREIGN KEY FK_887576ECA769DE27");
		$this->addSql("ALTER TABLE famelo_broensfin_domain_model_company_users_join DROP FOREIGN KEY FK_C68ACD68D01E5C72");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_claim");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_claim_users_join");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_claimstate");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_company");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_company_users_join");
		$this->addSql("DROP TABLE famelo_broensfin_domain_model_claimcomment");
	}
}