TYPO3:
  Flow:
    i18n:
      defaultLocale: de
      translationFallbacks:
        TYPO3.Form:
          - Famelo.Broensfin
          - TYPO3.Expose
          - TYPO3.Form
        TYPO3.Party:
          - Famelo.Saas
          - Famelo.Broensfin
          - TYPO3.Party
        TYPO3.Flow:
          - Famelo.Saas
          - Famelo.Broensfin
          - TYPO3.Party

  TYPO3CR:
    contentDimensions:
      locales:
        default: de_DE

  Neos:
    contentDimensions:
      dimensions:
        'locales':
          # The default preset to use if no URI segment was given when resolving locales in the routing
          defaultPreset: 'de_DE'
          label: 'Locales'
          icon: 'icon-language'
          presets:
            'all': ~
              # label: 'All languages'
              # values: ['mul_ZZ']
              # uriSegment: 'all'
            'en_GB':
              label: 'English'
              values: ['en_GB', 'en_ZZ', 'mul_ZZ']
              uriSegment: 'en'
            'de_DE':
              label: 'Deutsch'
              values: ['de_DE', 'de_ZZ', 'mul_ZZ']
              uriSegment: 'de'


Famelo:
  TranslationHelper:
    autoCreateTranslations: true
    autoCreationWhitelist:
      - Famelo.Saas
      - TYPO3.Expose