TYPO3:
  Flow:
    i18n:
      defaultLocale: de
      translationFallbacks:
        TYPO3.Expose:
          - Famelo.Broensfin
          - TYPO3.Expose
        TYPO3.Form:
          - Famelo.Broensfin
          - TYPO3.Expose
          - TYPO3.Form
        TYPO3.Party:
          - Famelo.Saas
          - Famelo.Broensfin
          - TYPO3.Party
        TYPO3.Flow:
          - Famelo.Saas
          - Famelo.Broensfin
          - TYPO3.Party

  # persistence:
    # doctrine:
      # filters:
        # 'my-filter-name': 'Acme\Demo\Filters\MyFilter'

  TYPO3CR:
    contentDimensions:
      locales:
        default: de_DE

  Neos:
    userInterface:
      # should minified JavaScript be loaded? For developing the TYPO3 Neos
      # Content Module, this should be set to FALSE.
      loadMinifiedJavascript: FALSE
    contentDimensions:
      dimensions:
        'locales':
          # The default preset to use if no URI segment was given when resolving locales in the routing
          defaultPreset: 'de_DE'
          label: 'Locales'
          icon: 'icon-language'
          presets:
            'all': ~
              # label: 'All languages'
              # values: ['mul_ZZ']
              # uriSegment: 'all'
            'de_DE':
              label: 'Deutsch'
              values: ['de_DE', 'de_ZZ', 'mul_ZZ']
              uriSegment: 'de'
            'en_GB':
              label: 'English'
              values: ['en_GB', 'en_ZZ', 'mul_ZZ']
              uriSegment: 'en'
    modules:
      management:
        submodules:
          customers:
            label: 'Customers'
            controller: '\TYPO3\Neos\Expose\Controller\ModuleController'
            description: 'Broensfin Customers'
            # icon: 'icon-th-large'
            resource: 'TYPO3_Neos_Backend_Module_Management_Workspaces'
            exposeController: 'List'
            exposeArguments:
              type: \Famelo\Saas\Domain\Model\User
          claims:
            label: 'Forderungen'
            controller: '\TYPO3\Neos\Expose\Controller\ModuleController'
            # icon: 'icon-th-large'
            resource: 'TYPO3_Neos_Backend_Module_Management_Workspaces'
            exposeController: 'List'
            exposeArguments:
              type: \Famelo\Broensfin\Domain\Model\Claim
          transactions:
            label: 'Transaktionen'
            controller: '\TYPO3\Neos\Expose\Controller\ModuleController'
            # icon: 'icon-th-large'
            resource: 'TYPO3_Neos_Backend_Module_Management_Workspaces'
            exposeController: 'List'
            exposeArguments:
              type: \Famelo\Saas\Domain\Model\Transaction

Famelo:
  TranslationHelper:
    autoCreateTranslations: true
    autoCreationWhitelist:
      - Famelo.Saas
      - Famelo.Broensfin
      - TYPO3.Expose