TYPO3:
  Flow:
    i18n:
      defaultLocale: de

  TYPO3CR:
    contentDimensions:
      locales:
        default: de_DE

  Neos:
    localization:
      localeMapping:
        all: ~
        de: [de_DE, de_ZZ, mul_ZZ]
        en: [en_ZZ, mul_ZZ]
      defaultLocaleIdentifier: de