TYPO3:
  Flow:
    i18n:
      defaultLocale: en

  TYPO3CR:
    contentDimensions:
      locales:
        default: mul_ZZ

  Neos:
    localization:
      localeMapping:
        de: [de_DE, de_ZZ, mul_ZZ]
        all: [en_ZZ, mul_ZZ]